import { docSort, effectSort, rankSort } from "../../helpers/utils.mjs";

/**
 * Options that describe documents.
 * @type {Record<string, {doc?: string, name: string, icon: string, doc?: string, sorter?: Function, getter?: string}>}
 */
export const documentOptions = {
  ability: {
    doc: "ActiveEffect",
    getter: "abilities",
    icon: "hand-sparkles",
    index: "abilities",
    name: "Ability",
    pack: "abilities",
    sorter: effectSort,
  },
  attunement: {
    doc: "ActiveEffect",
    getter: "attunements",
    icon: "handshake",
    name: "Attunement",
    sorter: docSort,
  },
  body: {
    doc: "Item",
    getter: "bodyParts",
    icon: "boot",
    index: "bodyParts",
    name: "Body Part",
    pack: "bodyParts",
    sorter: docSort,
  },
  character: {
    doc: "Actor",
    getter: "characters",
    icon: "user",
    name: "Character",
    sorter: docSort,
  },
  condition: {
    doc: "ActiveEffect",
    getter: "conditions",
    icon: "disease",
    index: "conditions",
    name: "Condition",
    sorter: docSort,
  },
  consequence: {
    doc: "ActiveEffect",
    getter: "consequences",
    icon: "explosion",
    name: "Consequence",
    sorter: docSort,
  },
  creature: {
    doc: "Actor",
    getter: "creatures",
    icon: "octopus",
    name: "Creature",
    pack: "creatures",
    sorter: docSort,
  },
  effect: {
    doc: "ActiveEffect",
    getter: "effects",
    icon: "disease",
    name: "Effect",
    sorter: docSort,
  },
  equipment: {
    doc: "Item",
    getter: "equipment",
    icon: "treasure-chest",
    index: "equipment",
    name: "Equipment",
    pack: "equipment",
    sorter: docSort,
  },
  fluency: {
    doc: "ActiveEffect",
    getter: "fluencies",
    icon: "compass-drafting",
    name: "Fluency",
    sorter: docSort,
  },
  mount: {
    doc: "Item",
    getter: "mounts",
    icon: "horse",
    name: "Mount",
    sorter: docSort,
  },
  power: {
    doc: "Item",
    getter: "powers",
    icon: "person-rays",
    name: "Power",
    sorter: docSort,
  },
  property: {
    doc: "ActiveEffect",
    getter: "properties",
    icon: "atom-simple",
    index: "properties",
    name: "Property",
    pack: "properties",
    sorter: effectSort,
  },
  protection: {
    icon: "shield-halved",
    name: "Protection",
  },
  rank: {
    doc: "Item",
    getter: "ranks",
    icon: "wreath-laurel",
    index: "classes",
    name: "Rank",
    pack: "classes",
    sorter: rankSort,
  },
  resource: {
    doc: "ActiveEffect",
    getter: "resources",
    icon: "hashtag",
    name: "Resource",
    sorter: docSort,
  },
  species: {
    doc: "Item",
    getter: "species",
    icon: "skull-cow",
    index: "creatures",
    name: "Species",
    pack: "species",
    sorter: docSort,
  },
};
