import { preLocalize } from "../../helpers/localization.mjs";
import { docSort, effectSort, rankSort } from "../../helpers/sort.mjs";
import { icons } from "../display/icons.mjs";

/**
 * Options that describe documents.
 * @type {Record<string, {doc?: string, name: string, icon: string, doc?: string, sorter?: Function, getter?: string}>}
 */
export const documentOptions = {
  ability: {
    doc: "ActiveEffect",
    getter: "abilities",
    icon: icons.document.ability,
    index: "abilities",
    name: "TYPES.ActiveEffect.ability",
    pack: "abilities",
    plural: "TERIOCK.DOCUMENTS.ability.plural",
    sorter: effectSort,
  },
  attunement: {
    doc: "ActiveEffect",
    getter: "attunements",
    icon: icons.document.attunement,
    name: "TYPES.ActiveEffect.attunement",
    plural: "TERIOCK.DOCUMENTS.attunement.plural",
    sorter: docSort,
  },
  body: {
    doc: "Item",
    getter: "bodyParts",
    icon: icons.document.body,
    index: "bodyParts",
    name: "TYPES.Item.body",
    pack: "bodyParts",
    plural: "TERIOCK.DOCUMENTS.body.plural",
    sorter: docSort,
  },
  character: {
    doc: "Actor",
    getter: "characters",
    icon: icons.document.character,
    name: "TYPES.Actor.character",
    plural: "TERIOCK.DOCUMENTS.character.plural",
    sorter: docSort,
  },
  condition: {
    doc: "ActiveEffect",
    getter: "conditions",
    icon: icons.document.condition,
    index: "conditions",
    name: "TYPES.ActiveEffect.condition",
    plural: "TERIOCK.DOCUMENTS.condition.plural",
    sorter: docSort,
  },
  consequence: {
    doc: "ActiveEffect",
    getter: "consequences",
    icon: icons.document.consequence,
    name: "TYPES.ActiveEffect.consequence",
    plural: "TERIOCK.DOCUMENTS.consequence.plural",
    sorter: docSort,
  },
  creature: {
    doc: "Actor",
    getter: "creatures",
    icon: icons.document.creature,
    name: "TYPES.Actor.creature",
    pack: "creatures",
    plural: "TERIOCK.DOCUMENTS.creature.plural",
    sorter: docSort,
  },
  damage: {
    doc: "JournalEntryPage",
    icon: icons.effect.damage,
    name: "TYPES.JournalEntryPage.damage",
    plural: "TERIOCK.DOCUMENTS.damage.plural",
  },
  drain: {
    doc: "JournalEntryPage",
    icon: icons.effect.drain,
    name: "TYPES.JournalEntryPage.drain",
    plural: "TERIOCK.DOCUMENTS.drain.plural",
  },
  effect: {
    doc: "ActiveEffect",
    getter: "effects",
    icon: icons.document.effect,
    name: "TYPES.ActiveEffect.effect",
    plural: "TERIOCK.DOCUMENTS.effect.plural",
    sorter: docSort,
  },
  equipment: {
    doc: "Item",
    getter: "equipment",
    icon: icons.document.equipment,
    index: "equipment",
    name: "TYPES.Item.equipment",
    pack: "equipment",
    plural: "TERIOCK.DOCUMENTS.equipment.plural",
    sorter: docSort,
  },
  fluency: {
    doc: "ActiveEffect",
    getter: "fluencies",
    icon: icons.document.fluency,
    name: "TYPES.ActiveEffect.fluency",
    plural: "TERIOCK.DOCUMENTS.fluency.plural",
    sorter: docSort,
  },
  mount: {
    doc: "Item",
    getter: "mounts",
    icon: icons.document.mount,
    name: "TYPES.Item.mount",
    plural: "TERIOCK.DOCUMENTS.mount.plural",
    sorter: docSort,
  },
  power: {
    doc: "Item",
    getter: "powers",
    icon: icons.document.power,
    name: "TYPES.Item.power",
    plural: "TERIOCK.DOCUMENTS.power.plural",
    sorter: docSort,
  },
  property: {
    doc: "ActiveEffect",
    getter: "properties",
    icon: icons.document.property,
    index: "properties",
    name: "TYPES.ActiveEffect.property",
    pack: "properties",
    plural: "TERIOCK.DOCUMENTS.property.plural",
    sorter: effectSort,
  },
  rank: {
    doc: "Item",
    getter: "ranks",
    icon: icons.document.rank,
    index: "classes",
    name: "TYPES.Item.rank",
    pack: "classes",
    plural: "TERIOCK.DOCUMENTS.rank.plural",
    sorter: rankSort,
  },
  resource: {
    doc: "ActiveEffect",
    getter: "resources",
    icon: icons.document.resource,
    name: "TYPES.ActiveEffect.resource",
    plural: "TERIOCK.DOCUMENTS.resource.plural",
    sorter: docSort,
  },
  species: {
    doc: "Item",
    getter: "species",
    icon: icons.document.species,
    index: "creatures",
    name: "TYPES.Item.species",
    pack: "species",
    plural: "TERIOCK.DOCUMENTS.species.plural",
    sorter: docSort,
  },
  stone: {
    doc: "Card",
    icon: icons.document.stone,
    name: "TYPES.Card.stone",
    plural: "TERIOCK.DOCUMENTS.stone.plural",
  },
  wrapper: {
    doc: "Item",
    icon: icons.document.ability,
    name: "TYPES.Item.wrapper",
    plural: "TERIOCK.DOCUMENTS.wrapper.plural",
  },
};

preLocalize("options.document", { keys: ["name", "plural"] });
