import { docSort, effectSort, rankSort } from "../../helpers/sort.mjs";
import { icons } from "../display/icons.mjs";

/**
 * Options that describe documents.
 * @type {Record<string, {doc?: string, name: string, icon: string, doc?: string, sorter?: Function, getter?: string}>}
 */
export const documentOptions = {
  ability: {
    doc: "ActiveEffect",
    getter: "abilities",
    icon: icons.document.ability,
    index: "abilities",
    name: "Ability",
    pack: "abilities",
    sorter: effectSort,
  },
  attunement: {
    doc: "ActiveEffect",
    getter: "attunements",
    icon: icons.document.attunement,
    name: "Attunement",
    sorter: docSort,
  },
  body: {
    doc: "Item",
    getter: "bodyParts",
    icon: icons.document.body,
    index: "bodyParts",
    name: "Body Part",
    pack: "bodyParts",
    sorter: docSort,
  },
  character: {
    doc: "Actor",
    getter: "characters",
    icon: icons.document.character,
    name: "Character",
    sorter: docSort,
  },
  condition: {
    doc: "ActiveEffect",
    getter: "conditions",
    icon: icons.document.condition,
    index: "conditions",
    name: "Condition",
    sorter: docSort,
  },
  consequence: {
    doc: "ActiveEffect",
    getter: "consequences",
    icon: icons.document.consequence,
    name: "Consequence",
    sorter: docSort,
  },
  creature: {
    doc: "Actor",
    getter: "creatures",
    icon: icons.document.creature,
    name: "Creature",
    pack: "creatures",
    sorter: docSort,
  },
  effect: {
    doc: "ActiveEffect",
    getter: "effects",
    icon: icons.document.effect,
    name: "Effect",
    sorter: docSort,
  },
  equipment: {
    doc: "Item",
    getter: "equipment",
    icon: icons.document.equipment,
    index: "equipment",
    name: "Equipment",
    pack: "equipment",
    sorter: docSort,
  },
  fluency: {
    doc: "ActiveEffect",
    getter: "fluencies",
    icon: icons.document.fluency,
    name: "Fluency",
    sorter: docSort,
  },
  mount: {
    doc: "Item",
    getter: "mounts",
    icon: icons.document.mount,
    name: "Mount",
    sorter: docSort,
  },
  power: {
    doc: "Item",
    getter: "powers",
    icon: icons.document.power,
    name: "Power",
    sorter: docSort,
  },
  property: {
    doc: "ActiveEffect",
    getter: "properties",
    icon: icons.document.property,
    index: "properties",
    name: "Property",
    pack: "properties",
    sorter: effectSort,
  },
  rank: {
    doc: "Item",
    getter: "ranks",
    icon: icons.document.rank,
    index: "classes",
    name: "Rank",
    pack: "classes",
    sorter: rankSort,
  },
  resource: {
    doc: "ActiveEffect",
    getter: "resources",
    icon: icons.document.resource,
    name: "Resource",
    sorter: docSort,
  },
  species: {
    doc: "Item",
    getter: "species",
    icon: icons.document.species,
    index: "creatures",
    name: "Species",
    pack: "species",
    sorter: docSort,
  },
  wrapper: {
    doc: "Item",
    icon: icons.document.ability,
  },
  stone: {
    doc: "Card",
    icon: icons.document.stone,
  },
};
