import * as index from "../index/_module.mjs";

export const equipmentOptions = {
  powerLevel: {
    mundane: {
      name: "Mundane",
      icon: "wand",
      color: "#986a44",
    },
    enchanted: {
      name: "Enchanted",
      icon: "wand-sparkles",
      color: "#3584e4",
    },
    magic: {
      name: "Magic",
      icon: "sparkles",
      color: "#9141ac",
    },
    unknown: {
      name: "Unknown",
      icon: "question",
      color: "#77767b",
    },
  },
  powerLevelShort: {
    mundane: "Mundane",
    enchanted: "Enchanted",
    magic: "Magic",
    unknown: "Unknown",
  },
  equipmentClasses: index.equipmentClasses,
  weaponFightingStyles: index.weaponFightingStyles,
  equipmentType: index.equipment,
  unidentifiedProperties: [
    "Ammunition",
    "AP",
    "AV0",
    "Bashing",
    "Bejeweled",
    "Blocking",
    "Burning",
    "Cumbersome",
    "Destroyed",
    "Flaming",
    "Fragile",
    "Glowing",
    "Loading",
    "Master Crafted",
    "Morganti",
    "Ranged",
    "Reach",
    "Searchable",
    "Shattered",
    "Small",
    "Snagging",
    "Special",
    "Thrown",
    "Two-Handed",
    "UB",
    "Versatile",
    "Weapon",
  ],
};
