import { icons } from "../display/icons.mjs";

export const takeOptions = {
  damage: {
    aliases: ["dmg"],
    apply: async (actor, amt) => await actor?.system.takeDamage(amt),
    icon: icons.effect.damage,
    label: "Damage",
    prefix: "Take",
    reverse: async (actor, amt) => await actor?.system.takeHealing(amt),
  },
  drain: {
    apply: async (actor, amt) => await actor?.system.takeDrain(amt),
    icon: icons.effect.drain,
    label: "Drain",
    prefix: "Take",
    reverse: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
  },
  wither: {
    apply: async (actor, amt) => await actor?.system.takeWither(amt),
    icon: icons.effect.wither,
    label: "Wither",
    prefix: "Take",
    reverse: async (actor, amt) => await actor?.system.takeWither(-amt),
  },
  healing: {
    apply: async (actor, amt) => await actor?.system.takeHealing(amt),
    icon: icons.effect.heal,
    label: "Healing",
    prefix: "Apply",
    reverse: async (actor, amt) => await actor?.system.takeDamage(amt),
  },
  revitalizing: {
    apply: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
    icon: icons.effect.revitalize,
    label: "Revitalizing",
    prefix: "Apply",
    reverse: async (actor, amt) => await actor?.system.takeDrain(amt),
  },
  setTempHp: {
    aliases: ["sth", "sthp"],
    apply: async (actor, amt) => await actor?.system.takeSetTempHp(amt),
    icon: icons.stat.hp,
    label: "Temp HP",
    prefix: "Set",
    reverse: async (actor) => await actor?.system.takeSetTempHp(0),
  },
  setTempMp: {
    aliases: ["stm", "stmp"],
    apply: async (actor, amt) => await actor?.system.takeGainTempHp(amt),
    icon: icons.stat.mp,
    label: "Temp MP",
    prefix: "Set",
    reverse: async (actor) => await actor?.system.takeSetTempHp(0),
  },
  gainTempHp: {
    aliases: ["gth", "gthp"],
    apply: async (actor, amt) => await actor?.system.takeSetTempMp(amt),
    icon: icons.stat.hp,
    label: "Temp HP",
    prefix: "Gain",
    reverse: async (actor) => await actor?.system.takeSetTempMp(0),
  },
  gainTempMp: {
    aliases: ["gtm", "gtmp"],
    apply: async (actor, amt) => await actor?.system.takeGainTempMp(amt),
    icon: icons.stat.mp,
    label: "Temp MP",
    prefix: "Gain",
    reverse: async (actor) => await actor?.system.takeSetTempMp(0),
  },
  sleep: {
    apply: async (actor, amt) => await actor?.system.takeSleep(amt),
    icon: icons.effect.sleep,
    label: "Sleep",
    prefix: "Test",
    reverse: async (actor) =>
      await actor?.toggleStatusEffect("asleep", { active: false }),
  },
  kill: {
    apply: async (actor, amt) => await actor?.system.takeKill(amt),
    icon: icons.effect.kill,
    label: "Kill",
    prefix: "Test",
    reverse: async (actor) =>
      await actor?.toggleStatusEffect("dead", { active: false }),
  },
  pay: {
    apply: async (actor, amt) => await actor?.system.takePay(amt),
    icon: icons.stat.gp,
    label: "Gold",
    prefix: "Pay",
    reverse: async (actor, amt) => await actor?.system.takePay(-amt),
  },
};
