import { preLocalize } from "../../helpers/localization.mjs";
import { icons } from "../display/icons.mjs";

export const takeOptions = {
  damage: {
    aliases: ["dmg"],
    apply: async (actor, amt) => await actor?.system.takeDamage(amt),
    icon: icons.effect.damage,
    label: "TERIOCK.EFFECTS.RollableEffects.damage.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.damage.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.damage.take",
    reverse: async (actor, amt) => await actor?.system.takeHealing(amt),
  },
  drain: {
    apply: async (actor, amt) => await actor?.system.takeDrain(amt),
    icon: icons.effect.drain,
    label: "TERIOCK.EFFECTS.RollableEffects.drain.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.drain.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.drain.take",
    reverse: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
  },
  wither: {
    apply: async (actor, amt) => await actor?.system.takeWither(amt),
    icon: icons.effect.wither,
    label: "TERIOCK.EFFECTS.RollableEffects.wither.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.wither.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.wither.take",
    reverse: async (actor, amt) => await actor?.system.takeWither(-amt),
  },
  healing: {
    apply: async (actor, amt) => await actor?.system.takeHealing(amt),
    icon: icons.effect.heal,
    label: "TERIOCK.EFFECTS.RollableEffects.heal.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.heal.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.heal.take",
    reverse: async (actor, amt) => await actor?.system.takeDamage(amt),
  },
  revitalizing: {
    apply: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
    icon: icons.effect.revitalize,
    label: "TERIOCK.EFFECTS.RollableEffects.revitalize.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.revitalize.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.revitalize.take",
    reverse: async (actor, amt) => await actor?.system.takeDrain(amt),
  },
  setTempHp: {
    aliases: ["sth", "sthp"],
    apply: async (actor, amt) => await actor?.system.takeSetTempHp(amt),
    icon: icons.stat.hp,
    label: "TERIOCK.EFFECTS.RollableEffects.setTempHp.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.setTempHp.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.setTempHp.take",
    reverse: async (actor) => await actor?.system.takeSetTempHp(0),
  },
  setTempMp: {
    aliases: ["stm", "stmp"],
    apply: async (actor, amt) => await actor?.system.takeGainTempHp(amt),
    icon: icons.stat.mp,
    label: "TERIOCK.EFFECTS.RollableEffects.setTempMp.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.setTempMp.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.setTempMp.take",
    reverse: async (actor) => await actor?.system.takeSetTempHp(0),
  },
  gainTempHp: {
    aliases: ["gth", "gthp"],
    apply: async (actor, amt) => await actor?.system.takeSetTempMp(amt),
    icon: icons.stat.hp,
    label: "TERIOCK.EFFECTS.RollableEffects.gainTempHp.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.gainTempHp.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.gainTempHp.take",
    reverse: async (actor) => await actor?.system.takeSetTempMp(0),
  },
  gainTempMp: {
    aliases: ["gtm", "gtmp"],
    apply: async (actor, amt) => await actor?.system.takeGainTempMp(amt),
    icon: icons.stat.mp,
    label: "TERIOCK.EFFECTS.RollableEffects.gainTempMp.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.gainTempMp.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.gainTempMp.take",
    reverse: async (actor) => await actor?.system.takeSetTempMp(0),
  },
  sleep: {
    apply: async (actor, amt) => await actor?.system.takeSleep(amt),
    icon: icons.effect.sleep,
    label: "TERIOCK.EFFECTS.RollableEffects.sleep.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.sleep.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.sleep.take",
    reverse: async (actor) =>
      await actor?.toggleStatusEffect("asleep", { active: false }),
  },
  kill: {
    apply: async (actor, amt) => await actor?.system.takeKill(amt),
    icon: icons.effect.kill,
    label: "TERIOCK.EFFECTS.RollableEffects.kill.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.kill.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.kill.take",
    reverse: async (actor) =>
      await actor?.toggleStatusEffect("dead", { active: false }),
  },
  pay: {
    apply: async (actor, amt) => await actor?.system.takePay(amt),
    icon: icons.stat.gp,
    label: "TERIOCK.EFFECTS.RollableEffects.pay.label",
    deal: "TERIOCK.EFFECTS.RollableEffects.pay.deal",
    take: "TERIOCK.EFFECTS.RollableEffects.pay.take",
    reverse: async (actor, amt) => await actor?.system.takePay(-amt),
  },
};

preLocalize("options.take", { keys: ["label", "deal", "take"] });
