export const characterTerms = {
  basics: {
    lvl: 'Level',
    hp: 'HP',
    mp: 'MP',
    pres: 'Presence',
    rank: 'Rank',
  },
  bonuses: {
    p: 'Proficiency',
    f: 'Fluency',
  },
  classRanks: {
    fla: 'Flame Mage Ranks',
    lif: 'Life Mage Ranks',
    nat: 'Nature Mage Ranks',
    nec: 'Necromancer Ranks',
    sto: 'Storm Mage Ranks',
    arc: 'Archer Ranks',
    ass: 'Assassin Ranks',
    cor: 'Corsair Ranks',
    ran: 'Ranger Ranks',
    thi: 'Thief Ranks',
    ber: 'Berserker Ranks',
    due: 'Duelist Ranks',
    kni: 'Knight Ranks',
    pal: 'Paladin Ranks',
    vet: 'Veteran Ranks',
  },
  archetypeRanks: {
    mag: 'Mage Ranks',
    sem: 'Semi Ranks',
    war: 'Warrior Ranks',
  },
  attributes: {
    int: 'INT',
    mov: 'MOV',
    per: 'PER',
    snk: 'SNK',
    str: 'STR',
    unp: 'UNP',
  },
  saves: {
    intSave: 'INT Save',
    strSave: 'STR Save',
    movSave: 'MOV Save',
    snkSave: 'SNK Save',
    perSave: 'PER Save',
    unpSave: 'UNP Save',
  },
  speeds: {
    walk: 'Walk Speed',
    diff: 'Difficult Terrain Speed',
    crawl: 'Crawl Speed',
    swim: 'Swim Speed',
    climb: 'Climb Speed',
    hide: 'Hidden Speed',
    leapHor: 'Leap Speed (Horizontal)',
    leapVer: 'Leap Speed (Vertical)',
    fly: 'Fly Speed',
    dig: 'Dig Speed',
    dive: 'Dive Speed',
  }
}