# File is based on:
# https://foundryvtt.wiki/en/development/guides/improving-intellisense

# Copy this file and rename it to "foundry-config.yaml"
installPath: "$HOME/Applications/Foundry/resources/app" # Root of your Foundry install, used for creating symlinks for type purposes
