/** @type {Teriock.UI.ThreeToggle} */
const threeToggleInitial = 0;

/**
 * @type {BaseActorSheetSettings}
 */
export const _defaultSheetSettings = {
  abilityFilters: {
    basic: threeToggleInitial,
    broken: threeToggleInitial,
    delivery: null,
    effects: null,
    element: null,
    expansion: threeToggleInitial,
    heightened: threeToggleInitial,
    hp: threeToggleInitial,
    interaction: null,
    invoked: threeToggleInitial,
    maneuver: null,
    material: threeToggleInitial,
    mp: threeToggleInitial,
    piercing: null,
    powerSource: null,
    ritual: threeToggleInitial,
    rotator: threeToggleInitial,
    search: "",
    skill: threeToggleInitial,
    somatic: threeToggleInitial,
    spell: threeToggleInitial,
    standard: threeToggleInitial,
    sustained: threeToggleInitial,
    target: null,
    verbal: threeToggleInitial,
  },
  abilitySortAscending: true,
  abilitySortOption: "name",
  conditionExpansions:
    /** @type {Record<Teriock.Parameters.Condition.ConditionKey, boolean>} */ {},
  equipmentFilters: {
    consumable: threeToggleInitial,
    equipmentClasses: null,
    equipped: threeToggleInitial,
    identified: threeToggleInitial,
    magicalProperties: null,
    materialProperties: null,
    powerLevel: null,
    properties: null,
    search: "",
    shattered: threeToggleInitial,
    weaponFightingStyles: null,
  },
  equipmentSortAscending: true,
  equipmentSortOption: "name",
  menus: {
    abilityFilters: false,
    abilityOptions: false,
    abilitySort: false,
    consequenceOptions: false,
    equipmentFilters: false,
    equipmentOptions: false,
    equipmentSort: false,
    fluencyOptions: false,
    powerOptions: false,
    rankOptions: false,
    resourceOptions: false,
  },
};
