export const iconStyles = {
  button: "solid",
  contextMenu: "solid",
  duotone: "duotone",
  fullWidth: "fw",
  light: "light",
  message: "light",
  regular: "regular",
  sharp: "sharp",
  sharpDuotone: "sharp-duotone",
  sheet: "light",
  solid: "solid",
  thin: "thin",
  title: "solid",
};
