export const icons = {
  ability: {
    adept: "ms-add",
    break: "ms-destruction",
    cost: "ms-toll",
    delivery: "ms-send",
    duration: "ms-timelapse",
    effectType: "ms-bolt",
    execution: "ms-start",
    expansion: "ms-open-run",
    expansionCap: "ms-bubble",
    expansionRange: "ms-straighten",
    gifted: "ms-remove",
    heightened: "ms-stat-3",
    inept: "ms-remove",
    interaction: "ms-swords",
    notOnUse: "ms-sync",
    onUse: "ms-sync-disabled",
    range: "ms-square-foot",
    scroll: "mdi-script",
    target: "ms-location-searching",
    unheightened: "ms-equal",
  },
  archetype: { everyman: "ms-accessibility", mage: "mdi-crystal-ball", semi: "ms-sprint", warrior: "mdi-mace" },
  armament: {
    ap: "ms-expand-circle-down",
    av: "mdi-shield-account",
    bv: "ms-shield",
    hitBonus: "ms-expand-circle-up",
    load: "ms-azm",
  },
  attribute: {
    int: "ms-neurology",
    mov: "ms-directions-run",
    per: "ms-visibility",
    snk: "ms-domino-mask",
    str: "ms-exercise",
    unp: "ms-self-improvement",
  },
  attunable: { attune: "ms-approval-delegation", deattune: "ms-approval-delegation-off", tier: "ms-trophy" },
  break: { destroy: "ms-destruction", reforge: "ms-hardware", repair: "ms-local-bar", shatter: "ms-no-drinks" },
  change: {
    key: "ms-search",
    phase: "ms-nest-clock-farsight-analog",
    priority: "ms-low-priority",
    target: "ms-recenter",
    type: "ms-calculate",
    value: "ms-subdirectory-arrow-right",
  },
  class: {
    archer: "mdi-bow-arrow",
    assassin: "ms-sports-martial-arts",
    berserker: "mdi-axe-battle",
    corsair: "ms-anchor",
    duelist: "ms-swords",
    flameMage: "ms-mode-heat",
    journeyman: "ms-hiking",
    knight: "mdi-sword",
    lifeMage: "ms-sunny",
    natureMage: "ms-nest-eco-leaf",
    necromancer: "ms-hand-bones",
    paladin: "ms-health-and-safety",
    ranger: "mdi-paw",
    stormMage: "ms-filter-drama",
    thief: "mdi-hand-coin",
    tradesman: "ms-home-repair-service",
    veteran: "ms-fort",
  },
  competence: { fluent: "ms-social-leaderboard", none: "ms-brightness-empty", proficient: "ms-license" },
  consequence: { crit: "ms-my-location", none: "ms-location-searching" },
  cover: { full: "ms-forest", half: "ms-grass", partial: "ms-park" },
  delivery: {
    aura: "ms-flare",
    bite: "ms-dentistry",
    cone: "ms-tornado",
    hand: "ms-front-hand",
    missile: "ms-bolt",
    sight: "ms-undereye",
  },
  document: {
    ability: "mdi-creation",
    archetype: "ms-stars",
    attunement: "ms-approval-delegation",
    body: "ms-rib-cage",
    character: "ms-person",
    condition: "ms-cyclone",
    consequence: "ms-graph-5",
    core: "ms-book-2",
    creature: "ms-owl",
    effect: "ms-microbiology",
    equipment: "ms-package-2",
    fluency: "mdi-ruler-square-compass",
    imbuement: "ms-graph-3",
    inventory: "ms-luggage",
    keyword: "ms-format-quote",
    macro: "ms-code",
    mount: "ms-chess-knight",
    power: "ms-person-celebrate",
    property: "ms-orbit",
    rank: "ms-military-tech",
    region: "ms-texture",
    resource: "ms-tag",
    species: "ms-genetics",
    stone: "ms-circle",
    table: "ms-table",
    tableResult: "ms-table-rows",
    token: "ms-account-circle",
  },
  effect: {
    awaken: "ms-sunny",
    damage: "mdi-heart-off",
    dealDamage: "ms-gavel",
    drain: "ms-format-color-reset",
    heal: "ms-volunteer-activism",
    immune: "ms-shield",
    kill: "ms-skull",
    protection: "mdi-shield-half-full",
    resist: "ms-shield",
    revitalize: "ms-water-drops",
    revive: "ms-cardiology",
    sleep: "ms-hotel",
    transform: "ms-nature",
    wither: "ms-hourglass-disabled",
  },
  equipment: {
    ammunition: "mdi-arrow-projectile-multiple",
    dampen: "ms-notifications-off",
    equipmentClasses: "ms-flag",
    equipmentType: "ms-shapes",
    glue: "ms-link",
    identify: "ms-visibility",
    maxCount: "ms-checkbook",
    maxWeight: "ms-backpack",
    minStr: "ms-exercise",
    readMagic: "ms-multimodal-hand-eye",
    stack: "ms-view-agenda",
    stash: "ms-inventory-2",
    storage: "ms-backpack",
    twoHanded: "ms-thumbs-up-down",
    undampen: "ms-notifications",
    unglue: "ms-link-off",
    unidentify: "ms-visibility-off",
    unstack: "ms-view-column-2",
    unstash: "ms-orders",
    weight: "ms-weight",
    weightMultiplier: "ms-close",
  },
  executionTime: {
    a0: "ms-exposure-zero",
    a1: "ms-timer-1",
    a2: "ms-timer-2",
    a3: "ms-timer-3",
    r0: "ms-exposure-zero",
    r1: "ms-timer-1",
  },
  expansionDelivery: {
    cascade: "ms-airline-stops",
    detonate: "ms-explosion",
    fork: "ms-arrow-split",
    ripple: "ms-circle-circle",
  },
  field: {
    artisan: "ms-design-services",
    mediator: "ms-diversity-3",
    prestige: "ms-diamond-shine",
    scholar: "ms-newsstand",
    survivalist: "ms-grass",
  },
  form: {
    echo: "ms-animation",
    flaw: "ms-block",
    gifted: "ms-hand-package",
    intrinsic: "ms-deployed-code",
    normal: "ms-nearby",
    special: "ms-star-shine",
  },
  hack: {
    arm: "ms-back-hand",
    body: "ms-pulmonology",
    ear: "ms-hearing-aid",
    eye: "ms-visibility",
    leg: "ms-barefoot",
    mouth: "ms-lips",
    nose: "ms-oxygen-saturation",
  },
  interaction: { attack: "ms-swords", block: "ms-shield", feat: "ms-star", manifest: "ms-flare" },
  maneuver: { active: "ms-arrow-right-alt", passive: "ms-cycle", reactive: "ms-redo", slow: "ms-airwave" },
  packs: {
    essentials: "mdi-ship-wheel",
    magicItems: "ms-experiment",
    maintenance: "ms-construction",
    playerUtilities: "ms-service-toolbox",
    templateEffects: "ms-design-services",
  },
  piercing: { av0: "ms-line-end-arrow-notch", none: "ms-close", ub: "ms-nat" },
  power: {
    backstory: "ms-person-book",
    blessing: "ms-folded-hands",
    curse: "ms-skull-list",
    deathScar: "ms-skull",
    familiar: "ms-pest-control-rodent",
    holiday: "ms-celebration",
    innate: "ms-person",
    learned: "ms-cognition-2",
    other: "ms-question-mark",
    pact: "ms-signature",
    traits: "ms-flag",
  },
  powerLevel: { enchanted: "ms-wand-shine", magic: "ms-wand-stars", mundane: "ms-candle", unknown: "ms-question-mark" },
  pseudoDocument: { automation: "ms-automation", expiration: "ms-av-timer", mechanic: "ms-settings-b-roll" },
  rank: { combatAbility: "ms-swords", supportAbility: "ms-shield-with-heart" },
  roll: { boost: "ms-arrow-warm-up", deboost: "ms-arrow-cool-down", reroll: "ms-replay" },
  settings: {
    alternateRules: "mdi-dice-multiple",
    automatedBehavior: "mdi-auto-fix",
    dialog: "mdi-script",
    display: "ms-display-settings",
    gameContent: "mdi-flask",
    gameMasterControls: "mdi-crown",
    tips: "mdi-message-alert",
  },
  species: {
    adult: "ms-account-child-invert",
    br: "ms-rubric",
    lifespan: "ms-elderly",
    maxSize: "ms-vertical-align-top",
    minSize: "ms-vertical-align-bottom",
    size: "ms-accessibility-new",
    traits: "ms-flag",
  },
  stat: { gp: "ms-poker-chip", hp: "ms-favorite", lp: "ms-hourglass", mp: "ms-water-drop" },
  target: {
    armor: "mdi-shield-account",
    item: "ms-candle",
    self: "ms-person",
    shield: "ms-shield",
    weapon: "mdi-knife-military",
  },
  tradecraft: {
    artist: "ms-palette",
    blacksmith: "mdi-anvil",
    builder: "ms-carpenter",
    cartographer: "ms-map",
    chef: "ms-chef-hat",
    courtier: "ms-conversation",
    diplomat: "ms-partner-exchange",
    enforcer: "ms-local-police",
    farmer: "ms-wheat",
    gambler: "ms-playing-cards",
    herbalist: "ms-local-florist",
    historian: "ms-shelves",
    hunter: "ms-target",
    innkeeper: "ms-night-shelter",
    investigator: "ms-search",
    locksmith: "ms-key",
    mariner: "ms-sailing",
    messenger: "ms-approval",
    metaphysicist: "ms-cognition",
    miner: "ms-diamond",
    peacekeeper: "ms-diversity-1",
    performer: "ms-theater-comedy",
    priest: "ms-folded-hands",
    scribe: "ms-history-edu",
    tailor: "ms-apparel",
    tamer: "ms-pets",
    teacher: "ms-school",
    tinkerer: "ms-build",
    tracker: "ms-footprint",
    trader: "ms-balance",
  },
  ui: {
    add: "ms-add",
    amount: "mdi-plus-minus",
    apply: "ms-forward",
    back: "ms-arrow-back",
    badge: "ms-label",
    chat: "ms-chat",
    collapse: "ms-collapse-all",
    compendium: "fa-book-atlas",
    configure: "ms-build",
    confirm: "ms-help",
    custom: "ms-dashboard-customize",
    d20: "ms-token",
    damage: "ms-gavel",
    deathBag: "ms-money-bag",
    delete: "ms-delete",
    details: "ms-format-list-bulleted",
    dice: "mdi-dice-multiple",
    disable: "ms-close",
    disabled: "ms-circle",
    document: "ms-description",
    done: "ms-check",
    duplicate: "ms-file-copy",
    edit: "ms-edit",
    enable: "ms-check",
    enabled: "ms-check-circle",
    expand: "ms-expand-all",
    filled0: "ms-circle",
    filled1: "ms-adjust",
    filled2: "ms-circle-circle",
    filter: "ms-filter-alt",
    flags: "ms-flag",
    formula: "ms-function",
    hack: "ms-rheumatology",
    hide: "ms-visibility-off",
    image: "ms-image",
    import: "ms-download",
    info: "ms-info",
    linked: "ms-link",
    locked: "ms-lock",
    longRest: "ms-camping",
    maximum: "ms-all-inclusive",
    menuClose: "ms-keyboard-arrow-up",
    menuOpen: "ms-keyboard-arrow-down",
    move: "ms-move-location",
    notes: "ms-book-5",
    numerical: "ms-tag",
    off: "ms-close",
    on: "ms-check",
    openWindow: "ms-open-in-new",
    options: "ms-tune",
    panel: "ms-toolbar",
    qualifier: "ms-mystery",
    quantity: "mdi-abacus",
    remove: "ms-close",
    reset: "ms-replay",
    save: "ms-save",
    select: "ms-check-circle",
    shareImage: "ms-mms",
    shareText: "ms-chat",
    sheet: "ms-ad-group",
    shortRest: "ms-fireplace",
    show: "ms-visibility",
    sort: "ms-sort",
    tabLeft: "ms-keyboard-double-arrow-left",
    tabRight: "ms-double-arrow",
    time: "ms-nest-clock-farsight-analog",
    toggle: "ms-toggle-on",
    undo: "ms-undo",
    unlocked: "ms-lock-open-right",
    unset: "ms-backspace",
    variable: "ms-question-mark",
    wiki: "ms-globe-book",
  },
};
