export const iconStyles = {
  button: "solid",
  contextMenu: "solid",
  duotone: "duotone",
  fullWidth: "fw",
  inline: "solid",
  light: "light",
  message: "solid",
  regular: "regular",
  sharp: "sharp",
  sharpDuotone: "sharp-duotone",
  sheet: "solid",
  sheetForm: "solid",
  solid: "solid",
  thin: "solid",
  title: "solid",
};
