export const icons = {
  ability: {
    break: "wine-glass-crack",
    delivery: "bow-arrow",
    duration: "hourglass",
    execution: "arrows-turn-right",
    expansion: "expand",
    expansionCap: "arrow-up-to-bracket",
    expansionRange: "ruler-combined",
    interaction: "swords",
    range: "ruler",
    target: "crosshairs-simple",
  },
  armament: {
    ap: "chevron-circle-down",
    av: "helmet-battle",
    bv: "shield",
    hitBonus: "plus",
  },
  attunable: {
    tier: "trophy",
  },
  break: {
    destroy: "burst",
    shatter: "wine-glass-crack",
  },
  cost: {
    gp: "coin",
    hp: "heart",
    mp: "droplet",
  },
  delivery: {
    aura: "sun",
    bite: "tooth",
    cone: "comet",
    hand: "hand",
    missile: "bolt",
    sight: "eye",
  },
  equipment: {
    maxCount: "abacus",
    maxWeight: "backpack",
    minStr: "dumbbell",
    weight: "weight-hanging",
    weightMultiplier: "xmark",
  },
  executionTime: {
    a0: "0",
    a1: "1",
    a2: "2",
    a3: "3",
    r0: "0",
    r1: "1",
  },
  expansionDelivery: {
    cascade: "arrows-turn-to-dots",
    detonate: "explosion",
    fork: "arrows-split-up-and-left",
    ripple: "circle-dot",
  },
  interaction: {
    attack: "crosshairs-simple",
    block: "shield",
    feat: "star",
    manifest: "magic",
  },
  maneuver: {
    active: "arrow-right",
    passive: "arrows-rotate",
    reactive: "arrow-turn-left",
    slow: "arrow-trend-down",
  },
  target: {
    armor: "helmet-battle",
    item: "ring",
    self: "user",
    shield: "shield",
    weapon: "sword",
  },
  ui: {
    add: "plus",
    formula: "function",
    hack: "axe",
    impacts: "flask-gear",
    menuClose: "chevron-up",
    menuOpen: "chevron-down",
    numerical: "hashtag",
    remove: "xmark",
    variable: "question",
  },
};
