import { hacksData } from "../data/hacks.mjs";

const tokenMagic = {
  burned: {
    filterType: "fire",
    filterId: "teriockConditionBurned",
    intensity: 1,
    color: 0xffffff,
    amplitude: 1,
    time: 0,
    blend: 2,
    fireBlend: 1,
    animated: {
      time: {
        active: true,
        speed: -0.0024,
        animType: "move",
      },
      intensity: {
        active: true,
        loopDuration: 15000,
        val1: 0.8,
        val2: 2,
        animType: "syncCosOscillation",
      },
      amplitude: {
        active: true,
        loopDuration: 4400,
        val1: 1,
        val2: 1.4,
        animType: "syncCosOscillation",
      },
    },
  },
  frozen: {
    filterType: "xfire",
    filterId: "teriockConditionFrozen",
    color: 0xacc5c5,
    time: 0,
    blend: 5,
    amplitude: 1,
    dispersion: 0,
    chromatic: false,
    scaleX: 1,
    scaleY: 1,
    inlay: true,
    animated: {
      time: {
        active: true,
        speed: -0.002,
        animType: "move",
      },
    },
  },
  hollied: {
    filterType: "xray",
    filterId: "teriockConditionHollied",
    time: 0,
    color: 0xffbb00,
    blend: 9,
    dimX: 1,
    dimY: 1,
    anchorX: 0,
    anchorY: 0,
    divisor: 36,
    intensity: 4,
    animated: {
      time: {
        active: true,
        speed: 0.0012,
        animType: "move",
      },
      anchorX: {
        animType: "syncCosOscillation",
        loopDuration: 6000,
        val1: 0.4,
        val2: 0.6,
      },
    },
  },
  terrored: {
    filterType: "xray",
    filterId: "teriockConditionTerrored",
    time: 0,
    color: 0xffffff,
    blend: 5,
    dimX: 20,
    dimY: 20,
    anchorX: 0.5,
    anchorY: 0,
    divisor: 8,
    intensity: 1,
    animated: {
      time: {
        active: true,
        speed: 0.00038,
        animType: "move",
      },
    },
  },
  lighted: {
    filterType: "ray",
    filterId: "teriockConditionLighted",
    time: 0,
    color: 0xcf8000,
    alpha: 0.5,
    divisor: 32,
    anchorX: 0,
    anchorY: 0,
    animated: {
      time: {
        active: true,
        speed: 0.0005,
        animType: "move",
      },
    },
  },
  ruined: {
    filterType: "splash",
    filterId: "teriockConditionRuined",
    color: 0x900505,
    padding: 30,
    time: Math.random() * 1000,
    seed: Math.random() / 100,
    splashFactor: 2,
    spread: 7,
    blend: 1,
    dimX: 1,
    dimY: 1,
    cut: true,
    textureAlphaBlend: false,
  },
  snared: {
    filterType: "web",
    filterId: "teriockConditionSnared",
    time: 100,
    div1: 20,
    div2: 10,
    animated: {
      time: {
        active: true,
        speed: 0.0005,
        animType: "move",
      },
    },
  },
  missileDodging: {
    filterType: "transform",
    filterId: "teriockConditionMissileDodging",
    padding: 50,
    animated: {
      translationY: {
        animType: "sinOscillation",
        val1: -0.125,
        val2: +0.125,
        loopDuration: 1200,
      },
      translationX: {
        animType: "cosOscillation",
        val1: -0.035,
        val2: +0.035,
        loopDuration: 1200,
      },
    },
  },
  meleeDodging: {
    filterType: "transform",
    filterId: "teriockConditionMeleeDodging",
    padding: 50,
    animated: {
      translationX: {
        animType: "sinOscillation",
        val1: -0.125,
        val2: +0.125,
        loopDuration: 1400,
      },
      translationY: {
        animType: "cosOscillation",
        val1: -0.035,
        val2: +0.035,
        loopDuration: 1400,
      },
    },
  },
  frenzied: {
    filterType: "outline",
    filterId: "teriockConditionFrenzied",
    padding: 10,
    color: 0xee6035,
    thickness: 1,
    quality: 5,
    zOrder: 9,
    animated: {
      thickness: {
        active: true,
        loopDuration: 800,
        animType: "syncCosOscillation",
        val1: 1,
        val2: 6,
      },
    },
  },
  ethereal: {
    filterType: "liquid",
    filterId: "teriockConditionEthereal",
    color: 0x20aaee,
    time: 0,
    blend: 8,
    intensity: 4,
    spectral: true,
    scale: 0.9,
    animated: {
      time: {
        active: true,
        speed: 0.001,
        animType: "move",
      },
      color: {
        active: true,
        loopDuration: 6000,
        animType: "colorOscillation",
        val1: 0xffffff,
        val2: 0x000000,
      },
    },
  },
  charmed: {
    filterType: "wave",
    filterId: "teriockConditionCharmed",
    time: 0,
    anchorX: 0.5,
    anchorY: 0.5,
    strength: 0.015,
    frequency: 120,
    color: 0xffffff,
    maxIntensity: 2.5,
    minIntensity: 0.9,
    padding: 10,
    animated: {
      time: {
        active: true,
        speed: 0.0085,
        animType: "move",
      },
      anchorX: {
        active: false,
        val1: 0.15,
        val2: 0.85,
        animType: "syncChaoticOscillation",
        loopDuration: 20000,
      },
      anchorY: {
        active: false,
        val1: 0.15,
        val2: 0.85,
        animType: "syncSinOscillation",
        loopDuration: 20000,
      },
    },
  },
  poisoned: {
    filterType: "ripples",
    filterId: "teriockConditionPoisoned",
    color: 0x508000,
    time: 0,
    alphaDiscard: false,
    zOrder: 50,
    animated: {
      time: {
        active: true,
        speed: 0.0009,
        animType: "move",
      },
    },
  },
};

for (const hack of Object.values(hacksData)) {
  tokenMagic[hack.id] = {
    filterType: "splash",
    filterId:
      "teriockCondition" + hack.id.at(0).toUpperCase() + hack.id.slice(1),
    rank: 5,
    color: 0x990505,
    padding: 80,
    time: Math.random() * 1000,
    seed: Math.random(),
    splashFactor: 1,
    spread: 0.4,
    blend: 1,
    dimX: 1,
    dimY: 1,
    cut: false,
    textureAlphaBlend: true,
    anchorX: 0.32 + Math.random() * 0.36,
    anchorY: 0.32 + Math.random() * 0.36,
  };
}

export default tokenMagic;
