import { hacks } from "../data.mjs";

const tokenMagic = {
  burned: {
    amplitude: 1,
    animated: {
      amplitude: { active: true, animType: "syncCosOscillation", loopDuration: 4400, val1: 1, val2: 1.4 },
      intensity: { active: true, animType: "syncCosOscillation", loopDuration: 15000, val1: 0.8, val2: 2 },
      time: { active: true, animType: "move", speed: -0.0024 },
    },
    blend: 2,
    color: 0xffffff,
    filterId: "teriockConditionBurned",
    filterType: "fire",
    fireBlend: 1,
    intensity: 1,
    time: 0,
  },
  charmed: {
    anchorX: 0.5,
    anchorY: 0.5,
    animated: {
      anchorX: { active: false, animType: "syncChaoticOscillation", loopDuration: 20000, val1: 0.15, val2: 0.85 },
      anchorY: { active: false, animType: "syncSinOscillation", loopDuration: 20000, val1: 0.15, val2: 0.85 },
      time: { active: true, animType: "move", speed: 0.0085 },
    },
    color: 0xffffff,
    filterId: "teriockConditionCharmed",
    filterType: "wave",
    frequency: 120,
    maxIntensity: 2.5,
    minIntensity: 0.9,
    padding: 10,
    strength: 0.015,
    time: 0,
  },
  ethereal: {
    animated: {
      color: { active: true, animType: "colorOscillation", loopDuration: 6000, val1: 0xffffff, val2: 0x000000 },
      time: { active: true, animType: "move", speed: 0.001 },
    },
    blend: 8,
    color: 0x20aaee,
    filterId: "teriockConditionEthereal",
    filterType: "liquid",
    intensity: 4,
    scale: 0.9,
    spectral: true,
    time: 0,
  },
  frenzied: {
    animated: { thickness: { active: true, animType: "syncCosOscillation", loopDuration: 800, val1: 1, val2: 6 } },
    color: 0xee6035,
    filterId: "teriockConditionFrenzied",
    filterType: "outline",
    padding: 10,
    quality: 5,
    thickness: 1,
    zOrder: 9,
  },
  frozen: {
    amplitude: 1,
    animated: { time: { active: true, animType: "move", speed: -0.002 } },
    blend: 5,
    chromatic: false,
    color: 0xacc5c5,
    dispersion: 0,
    filterId: "teriockConditionFrozen",
    filterType: "xfire",
    inlay: true,
    scaleX: 1,
    scaleY: 1,
    time: 0,
  },
  hollied: {
    anchorX: 0,
    anchorY: 0,
    animated: {
      anchorX: { animType: "syncCosOscillation", loopDuration: 6000, val1: 0.4, val2: 0.6 },
      time: { active: true, animType: "move", speed: 0.0012 },
    },
    blend: 9,
    color: 0xffbb00,
    dimX: 1,
    dimY: 1,
    divisor: 36,
    filterId: "teriockConditionHollied",
    filterType: "xray",
    intensity: 4,
    time: 0,
  },
  lighted: {
    alpha: 0.5,
    anchorX: 0,
    anchorY: 0,
    animated: { time: { active: true, animType: "move", speed: 0.0005 } },
    color: 0xcf8000,
    divisor: 32,
    filterId: "teriockConditionLighted",
    filterType: "ray",
    time: 0,
  },
  meleeDodging: {
    animated: {
      translationX: { animType: "sinOscillation", loopDuration: 1400, val1: -0.125, val2: +0.125 },
      translationY: { animType: "cosOscillation", loopDuration: 1400, val1: -0.035, val2: +0.035 },
    },
    filterId: "teriockConditionMeleeDodging",
    filterType: "transform",
    padding: 50,
  },
  missileDodging: {
    animated: {
      translationX: { animType: "cosOscillation", loopDuration: 1200, val1: -0.035, val2: +0.035 },
      translationY: { animType: "sinOscillation", loopDuration: 1200, val1: -0.125, val2: +0.125 },
    },
    filterId: "teriockConditionMissileDodging",
    filterType: "transform",
    padding: 50,
  },
  poisoned: {
    alphaDiscard: false,
    animated: { time: { active: true, animType: "move", speed: 0.0009 } },
    color: 0x508000,
    filterId: "teriockConditionPoisoned",
    filterType: "ripples",
    time: 0,
    zOrder: 50,
  },
  ruined: {
    blend: 1,
    color: 0x900505,
    cut: true,
    dimX: 1,
    dimY: 1,
    filterId: "teriockConditionRuined",
    filterType: "splash",
    padding: 30,
    seed: Math.random() / 100,
    splashFactor: 2,
    spread: 7,
    textureAlphaBlend: false,
    time: Math.random() * 1000,
  },
  snared: {
    animated: { time: { active: true, animType: "move", speed: 0.0005 } },
    div1: 20,
    div2: 10,
    filterId: "teriockConditionSnared",
    filterType: "web",
    time: 100,
  },
  terrored: {
    anchorX: 0.5,
    anchorY: 0,
    animated: { time: { active: true, animType: "move", speed: 0.00038 } },
    blend: 5,
    color: 0xffffff,
    dimX: 20,
    dimY: 20,
    divisor: 8,
    filterId: "teriockConditionTerrored",
    filterType: "xray",
    intensity: 1,
    time: 0,
  },
};

for (const hack of Object.values(hacks)) {
  tokenMagic[hack.id] = {
    anchorX: 0.32 + Math.random() * 0.36,
    anchorY: 0.32 + Math.random() * 0.36,
    blend: 1,
    color: 0x990505,
    cut: false,
    dimX: 1,
    dimY: 1,
    filterId: `teriockCondition${hack.id.at(0).toUpperCase()}${hack.id.slice(1)}`,
    filterType: "splash",
    padding: 80,
    rank: 5,
    seed: Math.random(),
    splashFactor: 1,
    spread: 0.4,
    textureAlphaBlend: true,
    time: Math.random() * 1000,
  };
}

export default tokenMagic;
