import { preLocalizeConfig } from "../../helpers/localization.mjs";
import { colors, images } from "../display/_module.mjs";

export default {
  categories: {
    abilities: {
      choices: "reference.abilities",
      format: "kebab",
      imgCategory: "abilities",
      label: "TYPES.ActiveEffect.ability",
      type: "ability",
    },
    bodyParts: {
      choices: "reference.bodyParts",
      format: "kebab",
      imgCategory: "bodyParts",
      label: "TYPES.Item.body",
      type: "body",
    },
    classes: {
      choices: "reference.classes",
      format: "kebab",
      imgCategory: "classes",
      label: "TYPES.JournalEntryPage.class",
      type: "class",
    },
    conditions: {
      choices: "reference.conditions",
      format: "camel",
      imgCategory: "conditions",
      label: "TYPES.ActiveEffect.condition",
      type: "condition",
    },
    damageTypes: {
      choices: "reference.damageTypes",
      format: "kebab",
      imgCategory: "damageTypes",
      label: "TYPES.JournalEntryPage.damage",
      type: "damage",
    },
    drainTypes: {
      choices: "reference.drainTypes",
      format: "kebab",
      imgCategory: "drainTypes",
      label: "TYPES.JournalEntryPage.drain",
      type: "drain",
    },
    effectTypes: {
      choices: "reference.effectTypes",
      format: "camel",
      imgCategory: "effectTypes",
      label: "TERIOCK.SYSTEMS.Metaphysics.FIELDS.effectTypes.label",
    },
    elements: {
      choices: "reference.elements",
      format: "camel",
      imgCategory: "elements",
      label: "TERIOCK.SYSTEMS.Metaphysics.FIELDS.elements.label",
    },
    equipment: {
      choices: "reference.equipment",
      format: "kebab",
      imgCategory: "equipment",
      label: "TYPES.Item.equipment",
      type: "equipment",
    },
    powerSources: {
      choices: "reference.powerSources",
      format: "camel",
      imgCategory: "effectTypes",
      label: "TERIOCK.SYSTEMS.Metaphysics.FIELDS.powerSources.label",
    },
    properties: {
      choices: "reference.properties",
      format: "kebab",
      imgCategory: "properties",
      label: "TYPES.ActiveEffect.property",
      type: "property",
    },
    species: {
      choices: "reference.creatures",
      format: "kebab",
      imgCategory: "creatures",
      label: "TYPES.Item.species",
      type: "species",
    },
    tradecrafts: {
      choices: "reference.tradecrafts",
      format: "camel",
      imgCategory: "tradecrafts",
      label: "TERIOCK.SHEETS.Actor.TABS.Tradecrafts.title",
    },

    other: { choices: "none", format: "none", imgCategory: "none", label: "TERIOCK.COMMON.Other" },
  },
  // no sort
  groups: {
    immunities: { label: "TERIOCK.SHEETS.Actor.TABS.Affinities.GROUPS.immunities", types: ["hexseal", "immunity"] },
    resistances: {
      label: "TERIOCK.SHEETS.Actor.TABS.Affinities.GROUPS.resistances",
      types: ["hexproof", "resistance", "vulnerability"],
    },
    boosts: { label: "TERIOCK.SHEETS.Actor.TABS.Affinities.GROUPS.boosts", types: ["takeDeboost", "takeBoost"] },
    bindings: { label: "TERIOCK.SHEETS.Actor.TABS.Affinities.GROUPS.bindings", types: ["binding"] },
    capabilities: {
      label: "TERIOCK.SHEETS.Actor.TABS.Affinities.GROUPS.capabilities",
      types: ["adeptitude", "ineptitude", "incapability"],
    },
  },
  // no sort
  types: {
    hexseal: {
      button: "TERIOCK.ROLLS.Hexseal.button",
      color: colors.palette.purple,
      hex: true,
      hook: "hexseal",
      identifier: "keyword:hexseal",
      img: images.manifest.effectTypes.hexseal,
      label: "TERIOCK.TERMS.Affinities.hexseal.single",
      protection: true,
    },
    immunity: {
      button: "TERIOCK.ROLLS.Immune.button",
      color: colors.palette.green,
      hook: "immune",
      identifier: "keyword:immunity",
      img: images.manifest.effectTypes.immunity,
      label: "TERIOCK.TERMS.Affinities.immunity.single",
      protection: true,
    },
    hexproof: {
      button: "TERIOCK.ROLLS.Hexproof.button",
      color: colors.palette.purple,
      competence: true,
      hex: true,
      hook: "hexproof",
      identifier: "keyword:hexproof",
      img: images.manifest.effectTypes.hexproof,
      label: "TERIOCK.TERMS.Affinities.hexproof.single",
      protection: true,
      threshold: true,
    },
    resistance: {
      button: "TERIOCK.ROLLS.Resist.button",
      color: colors.palette.green,
      competence: true,
      hook: "resist",
      identifier: "keyword:resistance",
      img: images.manifest.effectTypes.resistance,
      label: "TERIOCK.TERMS.Affinities.resistance.single",
      protection: true,
      threshold: true,
    },
    vulnerability: {
      color: colors.palette.red,
      identifier: "keyword:vulnerability",
      img: images.manifest.keywords.vulnerability,
      label: "TERIOCK.TERMS.Affinities.vulnerability.single",
      weakness: true,
    },
    takeBoost: {
      color: colors.palette.red,
      identifier: "keyword:boosted",
      img: images.manifest.keywords.boosted,
      label: "TERIOCK.TERMS.Affinities.takeBoost.single",
      stacking: true,
    },
    takeDeboost: {
      color: colors.palette.green,
      identifier: "keyword:deboosted",
      img: images.manifest.keywords.deboosted,
      label: "TERIOCK.TERMS.Affinities.takeDeboost.single",
      stacking: true,
    },
    binding: {
      color: colors.palette.red,
      identifier: "condition:bound",
      img: images.manifest.conditions.bound,
      label: "TERIOCK.TERMS.Affinities.binding.single",
      weakness: true,
    },
    adeptitude: {
      color: colors.palette.green,
      identifier: "keyword:adept",
      img: images.manifest.keywords.adept,
      label: "TERIOCK.TERMS.Affinities.adeptitude.single",
      stacking: true,
      tips: [{ level: "warning", text: "TERIOCK.TERMS.Affinities.adeptitude.tips.notAutomatic" }],
    },
    ineptitude: {
      color: colors.palette.red,
      identifier: "keyword:inept",
      img: images.manifest.keywords.inept,
      label: "TERIOCK.TERMS.Affinities.ineptitude.single",
      stacking: true,
      tips: [{ level: "warning", text: "TERIOCK.TERMS.Affinities.ineptitude.tips.notAutomatic" }],
    },
    incapability: {
      color: colors.palette.red,
      identifier: "keyword:incapable",
      img: images.manifest.keywords.incapable,
      label: "TERIOCK.TERMS.Affinities.incapability.single",
      tips: [{ level: "warning", text: "TERIOCK.TERMS.Affinities.incapability.tips.notAutomatic" }],
    },
  },
};

preLocalizeConfig("config.affinity.categories", { keys: ["label"] });
preLocalizeConfig("config.affinity.types", { key: "label", keys: ["label", "button"], sort: true });
