import { preLocalize } from "../../helpers/localization.mjs";
import { docSort, effectSort, rankSort } from "../../helpers/sort.mjs";
import { icons } from "../display/icons.mjs";

/**
 * Options that describe document types.
 * @satisfies {Record<string, Partial<Teriock.Config.DocumentEntry>>}
 */
export const documentConfig = {
  ability: {
    documentName: "ActiveEffect",
    getter: "abilities",
    icon: icons.document.ability,
    index: "abilities",
    label: "TYPES.ActiveEffect.ability",
    pack: "abilities",
    plural: "TERIOCK.DOCUMENTS.ability.plural",
    sorter: effectSort,
  },
  archetype: {
    documentName: "Item",
    getter: "archetypes",
    icon: icons.document.archetype,
    label: "TYPES.Item.archetype",
    plural: "TERIOCK.DOCUMENTS.archetype.plural",
    sorter: docSort,
  },
  attunement: {
    documentName: "ActiveEffect",
    getter: "attunements",
    icon: icons.document.attunement,
    label: "TYPES.ActiveEffect.attunement",
    plural: "TERIOCK.DOCUMENTS.attunement.plural",
    sorter: docSort,
  },
  body: {
    documentName: "Item",
    getter: "bodyParts",
    icon: icons.document.body,
    index: "bodyParts",
    label: "TYPES.Item.body",
    pack: "bodyParts",
    plural: "TERIOCK.DOCUMENTS.body.plural",
    sorter: docSort,
  },
  character: {
    documentName: "Actor",
    getter: "characters",
    icon: icons.document.character,
    label: "TYPES.Actor.character",
    plural: "TERIOCK.DOCUMENTS.character.plural",
    sorter: docSort,
  },
  condition: {
    documentName: "ActiveEffect",
    getter: "conditions",
    icon: icons.document.condition,
    index: "conditions",
    label: "TYPES.ActiveEffect.condition",
    plural: "TERIOCK.DOCUMENTS.condition.plural",
    sorter: docSort,
  },
  consequence: {
    documentName: "ActiveEffect",
    getter: "consequences",
    icon: icons.document.consequence,
    label: "TYPES.ActiveEffect.consequence",
    plural: "TERIOCK.DOCUMENTS.consequence.plural",
    sorter: docSort,
  },
  creature: {
    documentName: "Actor",
    getter: "creatures",
    icon: icons.document.creature,
    label: "TYPES.Actor.creature",
    pack: "creatures",
    plural: "TERIOCK.DOCUMENTS.creature.plural",
    sorter: docSort,
  },
  damage: {
    documentName: "JournalEntryPage",
    icon: icons.effect.damage,
    index: "damageTypes",
    label: "TYPES.JournalEntryPage.damage",
    plural: "TERIOCK.DOCUMENTS.damage.plural",
  },
  document: {
    icon: icons.ui.document,
    label: "TYPES.Base.document",
    plural: "TERIOCK.DOCUMENTS.document.plural",
  },
  drain: {
    documentName: "JournalEntryPage",
    icon: icons.effect.drain,
    index: "drainTypes",
    label: "TYPES.JournalEntryPage.drain",
    plural: "TERIOCK.DOCUMENTS.drain.plural",
  },
  effect: {
    documentName: "ActiveEffect",
    getter: "effects",
    icon: icons.document.effect,
    label: "TYPES.ActiveEffect.effect",
    plural: "TERIOCK.DOCUMENTS.effect.plural",
    sorter: docSort,
  },
  equipment: {
    documentName: "Item",
    getter: "equipment",
    icon: icons.document.equipment,
    index: "equipment",
    label: "TYPES.Item.equipment",
    pack: "equipment",
    plural: "TERIOCK.DOCUMENTS.equipment.plural",
    sorter: docSort,
  },
  fluency: {
    documentName: "ActiveEffect",
    getter: "fluencies",
    icon: icons.document.fluency,
    label: "TYPES.ActiveEffect.fluency",
    plural: "TERIOCK.DOCUMENTS.fluency.plural",
    sorter: docSort,
  },
  imbuement: {
    documentName: "ActiveEffect",
    getter: "imbuements",
    icon: icons.document.imbuement,
    label: "TYPES.ActiveEffect.imbuement",
    plural: "TERIOCK.DOCUMENTS.imbuement.plural",
    sorter: docSort,
  },
  inventory: {
    documentName: "Actor",
    getter: "inventories",
    icon: icons.document.inventory,
    label: "TYPES.Actor.inventory",
    plural: "TERIOCK.DOCUMENTS.inventory.plural",
    sorter: docSort,
  },
  mount: {
    documentName: "Item",
    getter: "mounts",
    icon: icons.document.mount,
    label: "TYPES.Item.mount",
    plural: "TERIOCK.DOCUMENTS.mount.plural",
    sorter: docSort,
  },
  power: {
    documentName: "Item",
    getter: "powers",
    icon: icons.document.power,
    label: "TYPES.Item.power",
    plural: "TERIOCK.DOCUMENTS.power.plural",
    sorter: docSort,
  },
  property: {
    documentName: "ActiveEffect",
    getter: "properties",
    icon: icons.document.property,
    index: "properties",
    label: "TYPES.ActiveEffect.property",
    pack: "properties",
    plural: "TERIOCK.DOCUMENTS.property.plural",
    sorter: effectSort,
  },
  rank: {
    documentName: "Item",
    getter: "ranks",
    icon: icons.document.rank,
    index: "classes",
    label: "TYPES.Item.rank",
    pack: "classes",
    plural: "TERIOCK.DOCUMENTS.rank.plural",
    sorter: rankSort,
  },
  resource: {
    documentName: "ActiveEffect",
    getter: "resources",
    icon: icons.document.resource,
    label: "TYPES.ActiveEffect.resource",
    plural: "TERIOCK.DOCUMENTS.resource.plural",
    sorter: docSort,
  },
  species: {
    documentName: "Item",
    getter: "species",
    icon: icons.document.species,
    index: "creatures",
    label: "TYPES.Item.species",
    pack: "species",
    plural: "TERIOCK.DOCUMENTS.species.plural",
    sorter: docSort,
  },
  stone: {
    documentName: "Card",
    icon: icons.document.stone,
    label: "TYPES.Card.stone",
    plural: "TERIOCK.DOCUMENTS.stone.plural",
  },
};

preLocalize("config.document", { keys: ["label", "plural"] });
