import {
  AbilityPreviewModel,
  EquipmentPreviewModel,
  FluencyPreviewModel,
  MetaphysicsPreviewModel,
} from "../../data/models/preview-models/_module.mjs";
import { preLocalize } from "../../helpers/localization.mjs";
import { docSort, effectSort, rankSort } from "../../helpers/sort.mjs";
import { icons } from "../display/icons.mjs";

/**
 * Options that describe document types.
 * @satisfies {Record<string, Partial<Teriock.Config.DocumentEntry>>}
 */
export default {
  ability: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "abilities",
    hint: "TERIOCK.DOCUMENTS.ability.hint",
    icon: icons.document.ability,
    index: "abilities",
    label: "TYPES.ActiveEffect.ability",
    pack: "abilities",
    plural: "TERIOCK.DOCUMENTS.ability.plural",
    previewModel: AbilityPreviewModel,
    sorter: effectSort,
  },
  archetype: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "archetypes",
    hint: "TERIOCK.DOCUMENTS.archetype.hint",
    icon: icons.document.archetype,
    label: "TYPES.Item.archetype",
    plural: "TERIOCK.DOCUMENTS.archetype.plural",
    sorter: docSort,
  },
  attunement: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "attunements",
    hint: "TERIOCK.DOCUMENTS.attunement.hint",
    icon: icons.document.attunement,
    label: "TYPES.ActiveEffect.attunement",
    plural: "TERIOCK.DOCUMENTS.attunement.plural",
    sorter: docSort,
  },
  base: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    hint: "TERIOCK.DOCUMENTS.base.hint",
    icon: icons.ability.effectType,
    label: "TYPES.ActiveEffect.base",
  },
  body: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "bodyParts",
    hint: "TERIOCK.DOCUMENTS.body.hint",
    icon: icons.document.body,
    index: "bodyParts",
    label: "TYPES.Item.body",
    pack: "bodyParts",
    plural: "TERIOCK.DOCUMENTS.body.plural",
    sorter: docSort,
  },
  character: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Actor",
    getter: "characters",
    hint: "TERIOCK.DOCUMENTS.character.hint",
    icon: icons.document.character,
    label: "TYPES.Actor.character",
    plural: "TERIOCK.DOCUMENTS.character.plural",
    sorter: docSort,
  },
  class: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "JournalEntryPage",
    hint: "TERIOCK.DOCUMENTS.class.hint",
    icon: icons.document.rank,
    index: "classes",
    label: "TYPES.JournalEntryPage.class",
    plural: "TERIOCK.DOCUMENTS.class.plural",
  },
  condition: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "conditions",
    hint: "TERIOCK.DOCUMENTS.condition.hint",
    icon: icons.document.condition,
    index: "conditions",
    label: "TYPES.ActiveEffect.condition",
    plural: "TERIOCK.DOCUMENTS.condition.plural",
    sorter: docSort,
  },
  consequence: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "consequences",
    hint: "TERIOCK.DOCUMENTS.consequence.hint",
    icon: icons.document.consequence,
    label: "TYPES.ActiveEffect.consequence",
    plural: "TERIOCK.DOCUMENTS.consequence.plural",
    sorter: docSort,
  },
  cover: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    hint: "TERIOCK.DOCUMENTS.cover.hint",
    icon: icons.cover.full,
    label: "TYPES.ActiveEffect.cover",
    plural: "TERIOCK.DOCUMENTS.cover.plural",
  },
  creature: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Actor",
    getter: "creatures",
    hint: "TERIOCK.DOCUMENTS.creature.hint",
    icon: icons.document.creature,
    label: "TYPES.Actor.creature",
    pack: "creatures",
    plural: "TERIOCK.DOCUMENTS.creature.plural",
    sorter: docSort,
  },
  damage: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "JournalEntryPage",
    hint: "TERIOCK.DOCUMENTS.damage.hint",
    icon: icons.effect.damage,
    index: "damageTypes",
    label: "TYPES.JournalEntryPage.damage",
    plural: "TERIOCK.DOCUMENTS.damage.plural",
  },
  document: /** @type {Teriock.Config.DocumentEntry} */ {
    icon: icons.ui.document,
    label: "TYPES.Document.base",
    plural: "TERIOCK.DOCUMENTS.document.plural",
  },
  drain: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "JournalEntryPage",
    hint: "TERIOCK.DOCUMENTS.drain.hint",
    icon: icons.effect.drain,
    index: "drainTypes",
    label: "TYPES.JournalEntryPage.drain",
    plural: "TERIOCK.DOCUMENTS.drain.plural",
  },
  effect: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "effects",
    icon: icons.document.effect,
    label: "TYPES.ActiveEffect.effect",
    plural: "TERIOCK.DOCUMENTS.effect.plural",
    sorter: docSort,
  },
  equipment: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "equipment",
    hint: "TERIOCK.DOCUMENTS.equipment.hint",
    icon: icons.document.equipment,
    index: "equipment",
    label: "TYPES.Item.equipment",
    pack: "equipment",
    plural: "TERIOCK.DOCUMENTS.equipment.plural",
    previewModel: EquipmentPreviewModel,
    sorter: docSort,
  },
  fluency: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "fluencies",
    hint: "TERIOCK.DOCUMENTS.fluency.hint",
    icon: icons.document.fluency,
    label: "TYPES.ActiveEffect.fluency",
    plural: "TERIOCK.DOCUMENTS.fluency.plural",
    previewModel: FluencyPreviewModel,
    sorter: docSort,
  },
  hack: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    hint: "TERIOCK.DOCUMENTS.hack.hint",
    icon: icons.ui.hack,
    label: "TYPES.ActiveEffect.hack",
    plural: "TERIOCK.DOCUMENTS.hack.plural",
  },
  imbuement: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "imbuements",
    hint: "TERIOCK.DOCUMENTS.imbuement.hint",
    icon: icons.document.imbuement,
    label: "TYPES.ActiveEffect.imbuement",
    plural: "TERIOCK.DOCUMENTS.imbuement.plural",
    sorter: docSort,
  },
  inventory: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Actor",
    getter: "inventories",
    hint: "TERIOCK.DOCUMENTS.inventory.hint",
    icon: icons.document.inventory,
    label: "TYPES.Actor.inventory",
    plural: "TERIOCK.DOCUMENTS.inventory.plural",
    sorter: docSort,
  },
  mount: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "mounts",
    hint: "TERIOCK.DOCUMENTS.mount.hint",
    icon: icons.document.mount,
    label: "TYPES.Item.mount",
    plural: "TERIOCK.DOCUMENTS.mount.plural",
    sorter: docSort,
  },
  power: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "powers",
    hint: "TERIOCK.DOCUMENTS.power.hint",
    icon: icons.document.power,
    label: "TYPES.Item.power",
    plural: "TERIOCK.DOCUMENTS.power.plural",
    sorter: docSort,
  },
  property: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "properties",
    hint: "TERIOCK.DOCUMENTS.property.hint",
    icon: icons.document.property,
    index: "properties",
    label: "TYPES.ActiveEffect.property",
    pack: "properties",
    plural: "TERIOCK.DOCUMENTS.property.plural",
    previewModel: MetaphysicsPreviewModel,
    sorter: effectSort,
  },
  rank: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "ranks",
    hint: "TERIOCK.DOCUMENTS.rank.hint",
    icon: icons.document.rank,
    index: "classes",
    label: "TYPES.Item.rank",
    pack: "classes",
    plural: "TERIOCK.DOCUMENTS.rank.plural",
    sorter: rankSort,
  },
  resource: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "ActiveEffect",
    getter: "resources",
    hint: "TERIOCK.DOCUMENTS.resource.hint",
    icon: icons.document.resource,
    label: "TYPES.ActiveEffect.resource",
    plural: "TERIOCK.DOCUMENTS.resource.plural",
    sorter: docSort,
  },
  rule: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "JournalEntryPage",
    hint: "TERIOCK.DOCUMENTS.rule.hint",
    icon: icons.document.core,
    label: "TYPES.JournalEntryPage.rule",
    plural: "TERIOCK.DOCUMENTS.rule.plural",
  },
  species: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Item",
    getter: "species",
    hint: "TERIOCK.DOCUMENTS.species.hint",
    icon: icons.document.species,
    index: "creatures",
    label: "TYPES.Item.species",
    pack: "species",
    plural: "TERIOCK.DOCUMENTS.species.plural",
    sorter: docSort,
  },
  stone: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "Card",
    hint: "TERIOCK.DOCUMENTS.stone.hint",
    icon: icons.document.stone,
    label: "TYPES.Card.stone",
    plural: "TERIOCK.DOCUMENTS.stone.plural",
  },
  tradecraft: /** @type {Teriock.Config.DocumentEntry} */ {
    documentName: "JournalEntryPage",
    hint: "TERIOCK.DOCUMENTS.tradecraft.hint",
    icon: icons.document.fluency,
    index: "tradecrafts",
    label: "TYPES.JournalEntryPage.tradecraft",
    plural: "TERIOCK.DOCUMENTS.tradecraft.plural",
  },
};

preLocalize("config.document", { keys: ["hint", "label", "plural"] });
