import { preLocalize } from "../../helpers/localization.mjs";
import { icons } from "../display/icons.mjs";

export const impactConfig = {
  damage: {
    aliases: ["dmg"],
    apply: async (actor, amt) => await actor?.system.takeDamage(amt),
    icon: icons.effect.damage,
    label: "TERIOCK.EFFECTS.Impacts.damage.label",
    deal: "TERIOCK.EFFECTS.Impacts.damage.deal",
    take: "TERIOCK.EFFECTS.Impacts.damage.take",
    reverse: async (actor, amt) => await actor?.system.takeHealing(amt),
  },
  drain: {
    apply: async (actor, amt) => await actor?.system.takeDrain(amt),
    icon: icons.effect.drain,
    label: "TERIOCK.EFFECTS.Impacts.drain.label",
    deal: "TERIOCK.EFFECTS.Impacts.drain.deal",
    take: "TERIOCK.EFFECTS.Impacts.drain.take",
    reverse: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
  },
  wither: {
    apply: async (actor, amt) => await actor?.system.takeWither(amt),
    icon: icons.effect.wither,
    label: "TERIOCK.EFFECTS.Impacts.wither.label",
    deal: "TERIOCK.EFFECTS.Impacts.wither.deal",
    take: "TERIOCK.EFFECTS.Impacts.wither.take",
    reverse: async (actor, amt) => await actor?.system.takeWither(-amt),
  },
  healing: {
    apply: async (actor, amt) => await actor?.system.takeHealing(amt),
    icon: icons.effect.heal,
    label: "TERIOCK.EFFECTS.Impacts.heal.label",
    deal: "TERIOCK.EFFECTS.Impacts.heal.deal",
    take: "TERIOCK.EFFECTS.Impacts.heal.take",
    reverse: async (actor, amt) => await actor?.system.takeDamage(amt),
  },
  revitalizing: {
    apply: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
    icon: icons.effect.revitalize,
    label: "TERIOCK.EFFECTS.Impacts.revitalize.label",
    deal: "TERIOCK.EFFECTS.Impacts.revitalize.deal",
    take: "TERIOCK.EFFECTS.Impacts.revitalize.take",
    reverse: async (actor, amt) => await actor?.system.takeDrain(amt),
  },
  setTempHp: {
    aliases: ["sth", "sthp"],
    apply: async (actor, amt) => await actor?.system.takeSetTempHp(amt),
    icon: icons.stat.hp,
    label: "TERIOCK.EFFECTS.Impacts.setTempHp.label",
    deal: "TERIOCK.EFFECTS.Impacts.setTempHp.deal",
    take: "TERIOCK.EFFECTS.Impacts.setTempHp.take",
    reverse: async (actor) => await actor?.system.takeSetTempHp(0),
  },
  setTempMp: {
    aliases: ["stm", "stmp"],
    apply: async (actor, amt) => await actor?.system.takeSetTempMp(amt),
    icon: icons.stat.mp,
    label: "TERIOCK.EFFECTS.Impacts.setTempMp.label",
    deal: "TERIOCK.EFFECTS.Impacts.setTempMp.deal",
    take: "TERIOCK.EFFECTS.Impacts.setTempMp.take",
    reverse: async (actor) => await actor?.system.takeSetTempHp(0),
  },
  gainTempHp: {
    aliases: ["gth", "gthp"],
    apply: async (actor, amt) => await actor?.system.takeGainTempHp(amt),
    icon: icons.stat.hp,
    label: "TERIOCK.EFFECTS.Impacts.gainTempHp.label",
    deal: "TERIOCK.EFFECTS.Impacts.gainTempHp.deal",
    take: "TERIOCK.EFFECTS.Impacts.gainTempHp.take",
    reverse: async (actor) => await actor?.system.takeSetTempMp(0),
  },
  gainTempMp: {
    aliases: ["gtm", "gtmp"],
    apply: async (actor, amt) => await actor?.system.takeGainTempMp(amt),
    icon: icons.stat.mp,
    label: "TERIOCK.EFFECTS.Impacts.gainTempMp.label",
    deal: "TERIOCK.EFFECTS.Impacts.gainTempMp.deal",
    take: "TERIOCK.EFFECTS.Impacts.gainTempMp.take",
    reverse: async (actor) => await actor?.system.takeSetTempMp(0),
  },
  sleep: {
    apply: async (actor, amt) => await actor?.system.takeSleep(amt),
    icon: icons.effect.sleep,
    label: "TERIOCK.EFFECTS.Impacts.sleep.label",
    deal: "TERIOCK.EFFECTS.Impacts.sleep.deal",
    take: "TERIOCK.EFFECTS.Impacts.sleep.take",
    reverse: async (actor) =>
      await actor?.toggleStatusEffect("asleep", { active: false }),
  },
  hide: {
    apply: async (actor, amt) => await actor?.system.takeHide(amt),
    icon: icons.ui.hide,
    label: "TERIOCK.EFFECTS.Impacts.hide.label",
    deal: "TERIOCK.EFFECTS.Impacts.hide.deal",
    take: "TERIOCK.EFFECTS.Impacts.hide.take",
    reverse: async (actor) => await actor?.system.takeHide(null),
  },
  perceive: {
    aliases: ["percieve"],
    apply: async (actor, amt) => await actor?.system.takePerceive(amt),
    icon: icons.ui.show,
    label: "TERIOCK.EFFECTS.Impacts.perceive.label",
    deal: "TERIOCK.EFFECTS.Impacts.perceive.deal",
    take: "TERIOCK.EFFECTS.Impacts.perceive.take",
    reverse: async (actor) => await actor?.system.takePerceive(null),
  },
  kill: {
    apply: async (actor, amt) => await actor?.system.takeKill(amt),
    icon: icons.effect.kill,
    label: "TERIOCK.EFFECTS.Impacts.kill.label",
    deal: "TERIOCK.EFFECTS.Impacts.kill.deal",
    take: "TERIOCK.EFFECTS.Impacts.kill.take",
    reverse: async (actor) =>
      await actor?.toggleStatusEffect("dead", { active: false }),
  },
  pay: {
    apply: async (actor, amt) => await actor?.system.takePay(amt),
    icon: icons.stat.gp,
    label: "TERIOCK.EFFECTS.Impacts.pay.label",
    deal: "TERIOCK.EFFECTS.Impacts.pay.deal",
    take: "TERIOCK.EFFECTS.Impacts.pay.take",
    reverse: async (actor, amt) => await actor?.system.takePay(-amt),
  },
  other: {
    apply: () => null,
    icon: icons.ui.dice,
    label: "TERIOCK.EFFECTS.Impacts.other.label",
    deal: "TERIOCK.EFFECTS.Impacts.other.label",
    take: "TERIOCK.EFFECTS.Impacts.other.label",
    reverse: () => null,
    hidden: true,
  },
};

preLocalize("config.impact", { keys: ["label", "deal", "take"] });
