import { preLocalizeConfig } from "../../helpers/localization.mjs";
import { icons } from "../display/_module.mjs";

export default {
  damage: /** @type {Teriock.Config.ImpactEntry} */ {
    aliases: ["dmg"],
    deal: "TERIOCK.EFFECTS.Impacts.damage.deal",
    harm: true,
    icon: icons.manifest.effect.damage,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.damage.label",
    min: 0,
    morganti: true,
    take: "TERIOCK.EFFECTS.Impacts.damage.take",
    apply: async (actor, amt, options) => await actor?.system.takeDamage(amt, options),
    reverse: async (actor, amt) => await actor?.system.takeHealing(amt),
  },
  drain: /** @type {Teriock.Config.ImpactEntry} */ {
    aliases: ["drn"],
    deal: "TERIOCK.EFFECTS.Impacts.drain.deal",
    harm: true,
    icon: icons.manifest.effect.drain,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.drain.label",
    min: 0,
    morganti: true,
    take: "TERIOCK.EFFECTS.Impacts.drain.take",
    apply: async (actor, amt, options) => await actor?.system.takeDrain(amt, options),
    reverse: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
  },
  wither: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.wither.deal",
    icon: icons.manifest.effect.wither,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.wither.label",
    take: "TERIOCK.EFFECTS.Impacts.wither.take",
    apply: async (actor, amt) => await actor?.system.takeWither(amt),
    reverse: async (actor, amt) => await actor?.system.takeWither(-amt),
  },

  healing: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.heal.deal",
    icon: icons.manifest.effect.heal,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.heal.label",
    min: 0,
    take: "TERIOCK.EFFECTS.Impacts.heal.take",
    apply: async (actor, amt) => await actor?.system.takeHealing(amt),
    reverse: async (actor, amt) => await actor?.system.takeDamage(amt),
  },
  revitalizing: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.revitalize.deal",
    icon: icons.manifest.effect.revitalize,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.revitalize.label",
    min: 0,
    take: "TERIOCK.EFFECTS.Impacts.revitalize.take",
    apply: async (actor, amt) => await actor?.system.takeRevitalizing(amt),
    reverse: async (actor, amt) => await actor?.system.takeDrain(amt),
  },

  gainTempHp: /** @type {Teriock.Config.ImpactEntry} */ {
    aliases: ["gth"],
    deal: "TERIOCK.EFFECTS.Impacts.gainTempHp.deal",
    icon: icons.manifest.stat.hp,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.gainTempHp.label",
    take: "TERIOCK.EFFECTS.Impacts.gainTempHp.take",
    apply: async (actor, amt) => await actor?.system.takeGainTempHp(amt),
    reverse: async (actor, amt) => await actor?.system.takeGainTempHp(-amt),
  },
  gainTempMp: /** @type {Teriock.Config.ImpactEntry} */ {
    aliases: ["gtm"],
    deal: "TERIOCK.EFFECTS.Impacts.gainTempMp.deal",
    icon: icons.manifest.stat.mp,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.gainTempMp.label",
    take: "TERIOCK.EFFECTS.Impacts.gainTempMp.take",
    apply: async (actor, amt) => await actor?.system.takeGainTempMp(amt),
    reverse: async (actor, amt) => await actor?.system.takeGainTempMp(-amt),
  },
  setTempHp: /** @type {Teriock.Config.ImpactEntry} */ {
    aliases: ["sth"],
    deal: "TERIOCK.EFFECTS.Impacts.setTempHp.deal",
    icon: icons.manifest.stat.hp,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.setTempHp.label",
    min: 0,
    take: "TERIOCK.EFFECTS.Impacts.setTempHp.take",
    apply: async (actor, amt) => await actor?.system.takeSetTempHp(amt),
    reverse: async actor => await actor?.system.takeSetTempHp(0),
  },
  setTempMp: /** @type {Teriock.Config.ImpactEntry} */ {
    aliases: ["stm"],
    deal: "TERIOCK.EFFECTS.Impacts.setTempMp.deal",
    icon: icons.manifest.stat.mp,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.setTempMp.label",
    min: 0,
    take: "TERIOCK.EFFECTS.Impacts.setTempMp.take",
    apply: async (actor, amt) => await actor?.system.takeSetTempMp(amt),
    reverse: async actor => await actor?.system.takeSetTempMp(0),
  },

  hide: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.hide.deal",
    icon: icons.manifest.ui.hide,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.hide.label",
    nullable: true,
    take: "TERIOCK.EFFECTS.Impacts.hide.take",
    apply: async (actor, amt) => await actor?.system.takeHide(amt),
    reverse: async actor => await actor?.system.takeHide(null),
  },
  perceive: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.perceive.deal",
    icon: icons.manifest.ui.show,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.perceive.label",
    nullable: true,
    take: "TERIOCK.EFFECTS.Impacts.perceive.take",
    apply: async (actor, amt) => await actor?.system.takePerceive(amt),
    reverse: async actor => await actor?.system.takePerceive(null),
  },

  kill: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.kill.deal",
    icon: icons.manifest.effect.kill,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.kill.label",
    take: "TERIOCK.EFFECTS.Impacts.kill.take",
    apply: async (actor, amt) => await actor?.system.takeKill(amt),
    reverse: async actor => await actor?.toggleStatusEffect("dead", { active: false }),
  },
  pay: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.pay.deal",
    icon: icons.manifest.stat.gp,
    label: "TERIOCK.EFFECTS.Impacts.pay.label",
    take: "TERIOCK.EFFECTS.Impacts.pay.take",
    apply: async (actor, amt) => await actor?.system.takePay(amt),
    reverse: async (actor, amt) => await actor?.system.takePay(-amt),
  },
  sleep: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.sleep.deal",
    icon: icons.manifest.effect.sleep,
    integer: true,
    label: "TERIOCK.EFFECTS.Impacts.sleep.label",
    take: "TERIOCK.EFFECTS.Impacts.sleep.take",
    apply: async (actor, amt) => await actor?.system.takeSleep(amt),
    reverse: async actor => await actor?.toggleStatusEffect("asleep", { active: false }),
  },

  other: /** @type {Teriock.Config.ImpactEntry} */ {
    deal: "TERIOCK.EFFECTS.Impacts.other.label",
    hidden: true,
    icon: icons.manifest.ui.dice,
    label: "TERIOCK.EFFECTS.Impacts.other.label",
    take: "TERIOCK.EFFECTS.Impacts.other.label",
    apply: () => null,
    reverse: () => null,
  },
};

preLocalizeConfig("config.impact", { keys: ["label", "deal", "take"] });
