import { icons } from "../display/icons.mjs";
import documentConfig from "./document-config.mjs";

export default {
  address: "https://wiki.teriock.com/index.php",
  namespaces: /** @type {Record<string,Teriock.Config.WikiNamespaceEntry>} */ {
    Ability: { icon: documentConfig.ability.icon, packs: ["teriock.abilities"], parentKey: "name", type: "ability" },
    Body: { icon: documentConfig.body.icon, packs: ["teriock.bodyParts"], parentKey: "name", type: "body" },
    Class: {
      collection: "pages",
      icon: documentConfig.rank.icon,
      identifierType: "class",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "rank",
    },
    Condition: {
      collection: "pages",
      icon: documentConfig.condition.icon,
      identifierType: "rule",
      index: "conditions",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "rule",
    },
    Core: {
      collection: "pages",
      icon: icons.document.core,
      identifierType: "core",
      index: "coreRules",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "rule",
    },
    Creature: {
      collection: null,
      icon: documentConfig.creature.icon,
      packs: ["teriock.creatures"],
      parentKey: "name",
      type: "creature",
    },
    Damage: {
      collection: "pages",
      icon: documentConfig.damage.icon,
      identifierType: "damage",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "damage",
    },
    Drain: {
      collection: "pages",
      icon: documentConfig.drain.icon,
      identifierType: "drain",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "drain",
    },
    Equipment: {
      icon: documentConfig.equipment.icon,
      packs: ["teriock.equipment"],
      parentKey: "name",
      type: "equipment",
    },
    Keyword: {
      collection: "pages",
      icon: icons.document.keyword,
      identifierType: "keyword",
      index: "keywords",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "rule",
    },
    Property: {
      icon: documentConfig.property.icon,
      index: "properties",
      packs: ["teriock.properties"],
      parentKey: "name",
      type: "property",
    },
    Tradecraft: {
      collection: "pages",
      icon: documentConfig.fluency.icon,
      identifierType: "tradecraft",
      packs: ["teriock.rules"],
      parentKey: "namespace",
      type: "text",
    },
  },
};
