/**
 * Default actor sheet display settings.
 * @type {BaseActorSheetSettings}
 */
export const _defaultSheetSettings = {
  menus: {
    abilityFilters: false,
    abilityOptions: false,
    abilitySort: false,
    equipmentFilters: false,
    equipmentOptions: false,
    equipmentSort: false,
    fluencyOptions: false,
    resourceOptions: false,
    rankOptions: false,
    powerOptions: false,
    effectOptions: false,
  },
  abilityFilters: {
    search: "",
    basic: 0,
    standard: 0,
    skill: 0,
    spell: 0,
    ritual: 0,
    rotator: 0,
    verbal: 0,
    somatic: 0,
    material: 0,
    invoked: 0,
    sustained: 0,
    broken: 0,
    hp: 0,
    mp: 0,
    heightened: 0,
    expansion: 0,
    maneuver: null,
    interaction: null,
    powerSource: null,
    element: null,
    effects: null,
    delivery: null,
    piercing: null,
    target: null,
  },
  equipmentFilters: {
    search: "",
    equipped: 0,
    shattered: 0,
    consumable: 0,
    identified: 0,
    properties: null,
    materialProperties: null,
    magicalProperties: null,
    weaponFightingStyles: null,
    equipmentClasses: null,
    powerLevel: null,
  },
  abilitySortOption: "name",
  abilitySortAscending: true,
  equipmentSortOption: "name",
  equipmentSortAscending: true,
  conditionExpansions: {},
};
